taylor = Artist.create!(name: "Taylor Swift")
taylor.songs.create!(title: "Trouble")
taylor.songs.create!(title: "Red")
taylor.songs.create!(title: "Style")

adele = Artist.create!(name: "Adele")
adele.songs.create!(title: "Hello")
adele.songs.create!(title: "Best For Last")
adele.songs.create!(title: "Send My Love")
adele.songs.create!(title: "Rolling In The Deep")

drake = Artist.create!(name: "Drake")
drake.songs.create!(title: "Passionfruit")
drake.songs.create!(title: "Take Care")
drake.songs.create!(title: "One Dance")